name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t bandung:5000/historian/ai:latest .
          docker push bandung:5000/historian/ai:latest

      - name: Run docker-compose
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "OPENAI_MODEL_NAME=gpt-4o" >> .env
          echo "SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}" >> .env
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env

          docker stack deploy -c docker-compose.yml historian
